### ISSUE TITLE
disconnecting due to GracefulDisconnect(InnerNodeOfSpvProofIsValidTx())

### ISSUE THREAD

**Issue by rldleblanc** [akhavr/electrum-dash#101]
I'm unable to completely load my wallet. I tried recovering the wallet using the seed, but it keeps disconnecting from the server, any server. Here is the output from the verbose setting.

I/n | network | connecting to electrum.leblancnet.us:50016:s as new interface
I/i | interface.[electrum.leblancnet.us:50016] | connection established. version: ['ElectrumX 1.13.0', '1.4']
I/i | interface.[electrum.leblancnet.us:50016] | set blockchain with height 1205294
I/i | interface.[electrum.leblancnet.us:50016] | skipping header 1205294
I/n | network | switching to electrum.leblancnet.us:50016:s
I | verifier.[dash] | requested merkle 57ed023fc295f099a755eef606dc585a542295e0d265061f460497efd2e49d04
I/n | network | fee_histogram []
I/n | network | fee_estimates {25: 1000, 10: 1000, 5: 1000, 2: 4433}
I | verifier.[dash] | 
I/i | interface.[electrum.leblancnet.us:50016] | disconnecting due to GracefulDisconnect(InnerNodeOfSpvProofIsValidTx())

**Comment by zebra-lucky** [comment]
Cause of the problem is a false positive on "Leaf-Node Vulnerability" attack:
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-June/016105.html

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/attachments/20180609/9f4f5b1f/attachment-0001.pdf

https://bitcoin.stackexchange.com/questions/76121/how-is-the-leaf-node-weakness-in-merkle-trees-exploitable/76122#76122

Trying found a solution on this problem.

**Comment by akhavr** [comment]
@rldleblanc  closing now.  Let me know if you're still experiencing the issue.
